<?php
// ═══ DB SETUP PAGE ═══
// Run this ONCE to create your database and tables.
// Delete or restrict access to this file after setup.

$setupDone = false;
$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    $host   = trim($_POST['db_host'] ?? 'localhost');
    $port   = trim($_POST['db_port'] ?? '3306');
    $user   = trim($_POST['db_user'] ?? 'root');
    $pass   = trim($_POST['db_pass'] ?? '');
    $dbname = trim($_POST['db_name'] ?? 'library_erp');

    if ($_POST['action'] === 'test') {
        try {
            $pdo = new PDO("mysql:host=$host;port=$port", $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $success = '✅ Connection successful! Database server is reachable.';
        } catch (PDOException $e) {
            $error = '❌ Connection failed: ' . $e->getMessage();
        }
    }

    if ($_POST['action'] === 'install') {
        try {
            $pdo = new PDO("mysql:host=$host;port=$port", $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbname` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$dbname`");

            $sql = file_get_contents(__DIR__ . '/config/schema.sql');
            // Execute each statement
            foreach (array_filter(array_map('trim', explode(';', $sql))) as $stmt) {
                if ($stmt) $pdo->exec($stmt);
            }

            // Write config file
            $configContent = "<?php\n// Auto-generated by setup.php\ndefine('DB_HOST', " . var_export($host, true) . ");\ndefine('DB_PORT', " . var_export($port, true) . ");\ndefine('DB_USER', " . var_export($user, true) . ");\ndefine('DB_PASS', " . var_export($pass, true) . ");\ndefine('DB_NAME', " . var_export($dbname, true) . ");\n";
            file_put_contents(__DIR__ . '/config/db.php', $configContent);

            $setupDone = true;
            $success = '✅ Database installed successfully! All tables created. Config saved.';
        } catch (PDOException $e) {
            $error = '❌ Installation failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OPTMS ERP — Database Setup</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/css/setup.css">
</head>
<body>
<div class="setup-wrap">
  <div class="setup-card">
    <div class="setup-header">
      <div class="logo-icon">📚</div>
      <h1>OPTMS Tech ERP</h1>
      <p class="subtitle">Database Setup Wizard</p>
      <div class="step-bar">
        <div class="step active">1. Configure</div>
        <div class="step-sep">→</div>
        <div class="step <?= $setupDone ? 'active' : '' ?>">2. Install</div>
        <div class="step-sep">→</div>
        <div class="step <?= $setupDone ? 'active' : '' ?>">3. Done</div>
      </div>
    </div>

    <?php if ($error): ?>
    <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
    <?php endif; ?>
    <?php if ($success): ?>
    <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
    <?php endif; ?>

    <?php if (!$setupDone): ?>
    <form method="POST" id="setupForm">
      <div class="section-title">Database Connection</div>
      <div class="form-grid">
        <div class="fg-item">
          <label>Database Host</label>
          <input type="text" name="db_host" value="localhost" placeholder="localhost" required>
        </div>
        <div class="fg-item">
          <label>Port</label>
          <input type="text" name="db_port" value="3306" placeholder="3306">
        </div>
        <div class="fg-item">
          <label>Username</label>
          <input type="text" name="db_user" value="root" placeholder="root" required>
        </div>
        <div class="fg-item">
          <label>Password</label>
          <input type="password" name="db_pass" placeholder="Leave blank if none">
        </div>
        <div class="fg-item full">
          <label>Database Name</label>
          <input type="text" name="db_name" value="library_erp" placeholder="library_erp" required>
          <span class="hint">Will be created automatically if it doesn't exist.</span>
        </div>
      </div>

      <div class="section-title" style="margin-top:20px">What will be created</div>
      <div class="table-list">
        <span class="tl-item">👥 users</span>
        <span class="tl-item">👨‍🎓 students</span>
        <span class="tl-item">🏫 batches</span>
        <span class="tl-item">📖 books</span>
        <span class="tl-item">🔄 transactions</span>
        <span class="tl-item">📋 attendance</span>
        <span class="tl-item">💰 fees</span>
        <span class="tl-item">💸 expenses</span>
        <span class="tl-item">🔔 notifications</span>
        <span class="tl-item">🧾 invoices</span>
        <span class="tl-item">⚙️ settings</span>
        <span class="tl-item">📜 activity_log</span>
      </div>

      <div class="btn-row">
        <button type="submit" name="action" value="test" class="btn btn-ghost">🔌 Test Connection</button>
        <button type="submit" name="action" value="install" class="btn btn-primary">🚀 Install Database</button>
      </div>
    </form>
    <?php else: ?>
    <div class="success-wrap">
      <div class="check-icon">✅</div>
      <h2>Setup Complete!</h2>
      <p>Your database is ready. Config file has been saved to <code>config/db.php</code>.</p>
      <div class="warning-box">⚠️ <strong>Security:</strong> Please delete or rename <code>setup.php</code> after logging in for the first time.</div>
      <a href="login.php" class="btn btn-primary" style="margin-top:18px;display:inline-block;text-decoration:none">→ Go to Login</a>
    </div>
    <?php endif; ?>
  </div>

  <div class="setup-footer">OPTMS Tech Library ERP v6.0 &nbsp;·&nbsp; PHP + MySQL</div>
</div>
</body>
</html>
