-- ═══ OPTMS TECH LIBRARY ERP — DATABASE SCHEMA ═══
-- Generated by setup.php

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(60) UNIQUE NOT NULL,
  `email` VARCHAR(120) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('admin','librarian','receptionist','accountant','staff') DEFAULT 'librarian',
  `phone` VARCHAR(20),
  `status` ENUM('active','inactive') DEFAULT 'active',
  `last_login` DATETIME,
  `permissions` JSON,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `batches` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(80) NOT NULL,
  `time_start` TIME,
  `time_end` TIME,
  `total_seats` INT DEFAULT 0,
  `occupied_seats` INT DEFAULT 0,
  `fee` DECIMAL(10,2) DEFAULT 0,
  `status` ENUM('open','full','closed') DEFAULT 'open',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `students` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `student_code` VARCHAR(30) UNIQUE NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60),
  `email` VARCHAR(120),
  `phone` VARCHAR(20),
  `address` TEXT,
  `batch_id` INT,
  `seat` VARCHAR(20),
  `student_type` ENUM('regular','part-time','online') DEFAULT 'regular',
  `base_fee` DECIMAL(10,2) DEFAULT 0,
  `discount` DECIMAL(10,2) DEFAULT 0,
  `net_fee` DECIMAL(10,2) DEFAULT 0,
  `paid_fee` DECIMAL(10,2) DEFAULT 0,
  `fee_status` ENUM('paid','partial','pending','overdue') DEFAULT 'pending',
  `due_date` DATE,
  `enroll_date` DATE DEFAULT (CURDATE()),
  `status` ENUM('active','inactive') DEFAULT 'active',
  `notes` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`batch_id`) REFERENCES `batches`(`id`) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `books` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `book_code` VARCHAR(30) UNIQUE NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `author` VARCHAR(120),
  `isbn` VARCHAR(30),
  `category` VARCHAR(60),
  `shelf` VARCHAR(30),
  `total_copies` INT DEFAULT 1,
  `available_copies` INT DEFAULT 1,
  `price` DECIMAL(10,2) DEFAULT 0,
  `description` TEXT,
  `status` ENUM('available','unavailable','lost') DEFAULT 'available',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `transactions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `transaction_code` VARCHAR(30) UNIQUE NOT NULL,
  `student_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `issue_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `return_date` DATE,
  `fine_amount` DECIMAL(10,2) DEFAULT 0,
  `fine_paid` DECIMAL(10,2) DEFAULT 0,
  `status` ENUM('issued','returned','overdue','lost') DEFAULT 'issued',
  `notes` TEXT,
  `issued_by` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `attendance` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `student_id` INT NOT NULL,
  `batch_id` INT,
  `date` DATE NOT NULL,
  `status` ENUM('present','absent','late','leave') DEFAULT 'present',
  `marked_by` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `uniq_att` (`student_id`, `date`),
  FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `fees` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `student_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_mode` ENUM('cash','online','upi','card','bank') DEFAULT 'cash',
  `payment_date` DATE DEFAULT (CURDATE()),
  `receipt_no` VARCHAR(40) UNIQUE,
  `notes` TEXT,
  `collected_by` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `invoices` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invoice_no` VARCHAR(40) UNIQUE NOT NULL,
  `student_id` INT NOT NULL,
  `issue_date` DATE DEFAULT (CURDATE()),
  `due_date` DATE,
  `amount` DECIMAL(10,2) NOT NULL,
  `discount` DECIMAL(10,2) DEFAULT 0,
  `net_amount` DECIMAL(10,2) NOT NULL,
  `status` ENUM('unpaid','paid','partial','cancelled') DEFAULT 'unpaid',
  `notes` TEXT,
  `created_by` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`student_id`) REFERENCES `students`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `expenses` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(150) NOT NULL,
  `category` ENUM('salary','rent','utilities','supplies','maintenance','other') DEFAULT 'other',
  `amount` DECIMAL(10,2) NOT NULL,
  `expense_date` DATE DEFAULT (CURDATE()),
  `paid_to` VARCHAR(100),
  `payment_mode` ENUM('cash','online','upi','card','bank') DEFAULT 'cash',
  `notes` TEXT,
  `added_by` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `type` ENUM('info','warning','success','error') DEFAULT 'info',
  `title` VARCHAR(150) NOT NULL,
  `message` TEXT,
  `is_read` TINYINT(1) DEFAULT 0,
  `user_id` INT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `setting_key` VARCHAR(80) UNIQUE NOT NULL,
  `setting_value` TEXT,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `activity_log` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT,
  `action` VARCHAR(200),
  `entity_type` VARCHAR(60),
  `entity_id` INT,
  `details` TEXT,
  `ip_address` VARCHAR(45),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ═══ DEFAULT ADMIN USER (password: admin123) ═══
INSERT IGNORE INTO `users` (`name`, `username`, `email`, `password`, `role`, `status`)
VALUES ('Admin User', 'admin', 'admin@optms.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin', 'active');

-- ═══ DEFAULT SETTINGS ═══
INSERT IGNORE INTO `settings` (`setting_key`, `setting_value`) VALUES
('library_name', 'OPTMS Tech Library'),
('fine_per_day', '5'),
('max_issue_days', '7'),
('whatsapp_number', ''),
('currency', 'INR'),
('academic_year', '2024-25');

-- ═══ SAMPLE BATCHES ═══
INSERT IGNORE INTO `batches` (`name`, `time_start`, `time_end`, `total_seats`, `fee`, `status`) VALUES
('Early Morning', '05:00:00', '08:00:00', 40, 1200, 'open'),
('Morning', '08:00:00', '12:00:00', 50, 1500, 'open'),
('Afternoon', '12:00:00', '16:00:00', 45, 1400, 'open'),
('Evening', '16:00:00', '20:00:00', 50, 1500, 'open'),
('Night', '20:00:00', '23:00:00', 30, 1100, 'open');
